Fix Timezones for non-USE_TZ Django Instances.
myvr/django-celery-beat pull request #1
Opened 2018-08-28 21:15 UTC by GeorgeSpark-Stahl

1) Use Celery app.now for celery.beat schedulers.
2) Strip TZ from last_run_time on save if non USE_TZ instance.

2018-08-28 21:24 UTC, GeorgeSpark-Stahl reviewed
I tested this locally by:

1) installing rabbitmq-server `sudo apt-get install rabbitmq-server`
2) disabling all the tasks but 1
3) Short circuit that app to occasionally fail.
4) run celery worker and celery beat
5) watch the logs

> *[Reviewable](https://reviewable.io/reviews/myvr/django-celery-beat/1#-:-LL1PDK6-ewyMFLum2gX:bbtewxg)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @jkasky)



<!-- Sent from Reviewable.io -->

2018-08-28 21:27 UTC, GeorgeSpark-Stahl reviewed
Ohh, and disable CELERY_TASK_ALWAYS_EAGER

> *[Reviewable](https://reviewable.io/reviews/myvr/django-celery-beat/1#-:-LL1Qdth90KUDJh_2411:bywy610)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @jkasky)



<!-- Sent from Reviewable.io -->

2018-08-28 21:40 UTC, jkasky requested changes
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/myvr/django-celery-beat/1)* status: all files reviewed, 4 unresolved discussions (waiting on @GeorgeSpark-Stahl)

___
*[django_celery_beat/utils.py, line 16 at r1](https://reviewable.io/reviews/myvr/django-celery-beat/1#-LL1P76c28zuKgFeB8q5:-LL1P76c28zuKgFeB8q6:bi6i919) ([raw file](https://github.com/myvr/django-celery-beat/blob/fddf53c03eb4ae3921506311a4d7e51d04c7ea2c/django_celery_beat/utils.py#L16)):*
> ```Python
> 
> def make_aware(value):
>     """Force datetime to have timezone information."""
> ```

leave this typo,  focus the commit on our customization without cleaning up others
___
*[django_celery_beat/utils.py, line 27 at r1](https://reviewable.io/reviews/myvr/django-celery-beat/1#-LL1OnF28f7UodXgQjcx:-LL1OnF28f7UodXgQjcy:b-it1gki) ([raw file](https://github.com/myvr/django-celery-beat/blob/fddf53c03eb4ae3921506311a4d7e51d04c7ea2c/django_celery_beat/utils.py#L27)):*
> ```Python
> 
> 
> def fix_for_database(value):
> ```

Would `maybe_make_unaware` be a better name that is more consistent with make_aware?
___
*[django_celery_beat/utils.py, line 28 at r1](https://reviewable.io/reviews/myvr/django-celery-beat/1#-LL1Ou_l1W1jzoKhdfBR:-LL1Ou_l1W1jzoKhdfBS:b-vmo53) ([raw file](https://github.com/myvr/django-celery-beat/blob/fddf53c03eb4ae3921506311a4d7e51d04c7ea2c/django_celery_beat/utils.py#L28)):*
> ```Python
> 
> def fix_for_database(value):
>     """ Fix datetime values for configured database.  """
> ```

Also, this comment should be consistent with the project/module. Most Python doc comments do NOT pad the comment with spacing, it's a style adopted by a few at MyVR for some reason.
___
*[django_celery_beat/utils.py, line 32 at r1](https://reviewable.io/reviews/myvr/django-celery-beat/1#-LL1TZFNC5zkU2_lULQp:-LL1TZFNC5zkU2_lULQq:b7v0uuq) ([raw file](https://github.com/myvr/django-celery-beat/blob/fddf53c03eb4ae3921506311a4d7e51d04c7ea2c/django_celery_beat/utils.py#L32)):*
> ```Python
>         value = make_aware(value)
>     else:
>         value = value.replace(tzinfo=None)
> ```

If the value is aware should we (or do we have too) call make_aware to convert to Django default TIME_ZONE first before removing the tzinfo?


<!-- Sent from Reviewable.io -->

2018-08-28 21:47 UTC, jkasky reviewed
Looks like there are some tests to run as well.

> *[Reviewable](https://reviewable.io/reviews/myvr/django-celery-beat/1#-:-LL1VA_h9xs-3Zew_zUC:b-zed48v)* status: all files reviewed, 4 unresolved discussions (waiting on @GeorgeSpark-Stahl)



<!-- Sent from Reviewable.io -->

2018-08-28 21:54 UTC, jkasky requested changes
> *[Reviewable](https://reviewable.io/reviews/myvr/django-celery-beat/1)* status: all files reviewed, 5 unresolved discussions (waiting on @GeorgeSpark-Stahl)

___
*[django_celery_beat/models.py, line 310 at r1](https://reviewable.io/reviews/myvr/django-celery-beat/1#-LL1WZmSD1JwqNKxvTvP:-LL1WZmSD1JwqNKxvTvQ:b9mtdvr) ([raw file](https://github.com/myvr/django-celery-beat/blob/fddf53c03eb4ae3921506311a4d7e51d04c7ea2c/django_celery_beat/models.py#L310)):*
> ```Python
>         self.routing_key = self.routing_key or None
>         self.queue = self.queue or None
>         self.last_run_at = fix_for_database(self.last_run_at)
> ```

This should probably be:

```python
if self.last_run_at:
    ...
```

If one were to disable a task, then edit (e.g. change schedule), it would cause a NoneType error.


<!-- Sent from Reviewable.io -->

2018-08-28 22:10 UTC, GeorgeSpark-Stahl reviewed
Ooh, yeah I'll check that out.

> *[Reviewable](https://reviewable.io/reviews/myvr/django-celery-beat/1#-:-LL1_ZLi924m_4CABu8S:b-8motu3)* status: all files reviewed, 5 unresolved discussions (waiting on @jkasky and @GeorgeSpark-Stahl)

___
*[django_celery_beat/models.py, line 310 at r1](https://reviewable.io/reviews/myvr/django-celery-beat/1#-LL1WZmSD1JwqNKxvTvP:-LL1_HoBAvtuIfhh59iq:b-8o5hdk) ([raw file](https://github.com/myvr/django-celery-beat/blob/fddf53c03eb4ae3921506311a4d7e51d04c7ea2c/django_celery_beat/models.py#L310)):*
<details><summary><i>Previously, jkasky (Jesse Kasky) wrote…</i></summary><blockquote>

This should probably be:

```python
if self.last_run_at:
    ...
```

If one were to disable a task, then edit (e.g. change schedule), it would cause a NoneType error.
</blockquote></details>

Good point, done
___
*[django_celery_beat/utils.py, line 16 at r1](https://reviewable.io/reviews/myvr/django-celery-beat/1#-LL1P76c28zuKgFeB8q5:-LL1WJ9_3AmVLneJZFK6:b-896fix) ([raw file](https://github.com/myvr/django-celery-beat/blob/fddf53c03eb4ae3921506311a4d7e51d04c7ea2c/django_celery_beat/utils.py#L16)):*
<details><summary><i>Previously, jkasky (Jesse Kasky) wrote…</i></summary><blockquote>

leave this typo,  focus the commit on our customization without cleaning up others
</blockquote></details>

Done.
___
*[django_celery_beat/utils.py, line 27 at r1](https://reviewable.io/reviews/myvr/django-celery-beat/1#-LL1OnF28f7UodXgQjcx:-LL1Wge9C28fNx-l9hBE:b-896fix) ([raw file](https://github.com/myvr/django-celery-beat/blob/fddf53c03eb4ae3921506311a4d7e51d04c7ea2c/django_celery_beat/utils.py#L27)):*
<details><summary><i>Previously, jkasky (Jesse Kasky) wrote…</i></summary><blockquote>

Would `maybe_make_unaware` be a better name that is more consistent with make_aware?
</blockquote></details>

Done.
___
*[django_celery_beat/utils.py, line 28 at r1](https://reviewable.io/reviews/myvr/django-celery-beat/1#-LL1Ou_l1W1jzoKhdfBR:-LL1Wmmh4Iu7TlPAIvUQ:b-896fix) ([raw file](https://github.com/myvr/django-celery-beat/blob/fddf53c03eb4ae3921506311a4d7e51d04c7ea2c/django_celery_beat/utils.py#L28)):*
<details><summary><i>Previously, jkasky (Jesse Kasky) wrote…</i></summary><blockquote>

Also, this comment should be consistent with the project/module. Most Python doc comments do NOT pad the comment with spacing, it's a style adopted by a few at MyVR for some reason.
</blockquote></details>

Done.
___
*[django_celery_beat/utils.py, line 32 at r1](https://reviewable.io/reviews/myvr/django-celery-beat/1#-LL1TZFNC5zkU2_lULQp:-LL1ZpLj7KMQmlYsk1N7:bs7b8e6) ([raw file](https://github.com/myvr/django-celery-beat/blob/fddf53c03eb4ae3921506311a4d7e51d04c7ea2c/django_celery_beat/utils.py#L32)):*
<details><summary><i>Previously, jkasky (Jesse Kasky) wrote…</i></summary><blockquote>

If the value is aware should we (or do we have too) call make_aware to convert to Django default TIME_ZONE first before removing the tzinfo?
</blockquote></details>

The value coming into this should be in the tz of CELERY_TIME_ZONE which in our case matches TIME_ZONE.  If it didn't, yeah we'd probably want to convert it to TIME_ZONE before we removed the tz.  I'll do that.


<!-- Sent from Reviewable.io -->

2018-08-28 23:04 UTC, GeorgeSpark-Stahl reviewed
Tox appears to be hanging(well, the test could be hanging) on my branch and the 1.1.1 version.  Looking into it.

> *[Reviewable](https://reviewable.io/reviews/myvr/django-celery-beat/1#-:-LL1lttBCaBJOtlA3ydY:bl5qmfq)* status: all files reviewed, 5 unresolved discussions (waiting on @jkasky)

___
*[django_celery_beat/utils.py, line 32 at r1](https://reviewable.io/reviews/myvr/django-celery-beat/1#-LL1TZFNC5zkU2_lULQp:-LL1aqDTBFHwNycb2BBu:b-896fix) ([raw file](https://github.com/myvr/django-celery-beat/blob/fddf53c03eb4ae3921506311a4d7e51d04c7ea2c/django_celery_beat/utils.py#L32)):*
<details><summary><i>Previously, GeorgeSpark-Stahl (George Spark-Stahl) wrote…</i></summary><blockquote>

The value coming into this should be in the tz of CELERY_TIME_ZONE which in our case matches TIME_ZONE.  If it didn't, yeah we'd probably want to convert it to TIME_ZONE before we removed the tz.  I'll do that.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2018-08-29 18:39 UTC, GeorgeSpark-Stahl reviewed
Had to install rabbitmq so it could actually trigger and commit a task.  That's done, tests look good.  I didn't install all the versions of django and python they are testing, but all the ones I had installed passed.

> *[Reviewable](https://reviewable.io/reviews/myvr/django-celery-beat/1#-:-LL5yZGk6Itxvpbc-HkJ:b-qj5k3h)* status: 0 of 2 files reviewed, 5 unresolved discussions (waiting on @jkasky)



<!-- Sent from Reviewable.io -->

2018-08-29 21:37 UTC, jkasky requested changes
> Reviewed 1 of 2 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/myvr/django-celery-beat/1)* status: all files reviewed, 1 unresolved discussion (waiting on @GeorgeSpark-Stahl)

___
*[django_celery_beat/utils.py, line 34 at r3](https://reviewable.io/reviews/myvr/django-celery-beat/1#-LL6bAtSAkmqRTES_Adx:-LL6bAtSAkmqRTES_Ady:b1o2qzj) ([raw file](https://github.com/myvr/django-celery-beat/blob/d7e39d59af718fa3df94412dd295c4ce632231ae/django_celery_beat/utils.py#L34)):*
> ```Python
> def maybe_make_unaware(value):
>     """Remove tz if not configured."""
>     if not getattr(settings, 'USE_TZ', False):
> ```

`and timezone.is_aware(value):`

Just a safeguard, `timezone.localtime` calls `value.astimezone` which will fail if you pass an unaware timezone because it can't convert an unaware value to another timezone.


<!-- Sent from Reviewable.io -->

2018-08-29 21:45 UTC, GeorgeSpark-Stahl reviewed
> *[Reviewable](https://reviewable.io/reviews/myvr/django-celery-beat/1)* status: all files reviewed, 1 unresolved discussion (waiting on @GeorgeSpark-Stahl)

___
*[django_celery_beat/utils.py, line 34 at r3](https://reviewable.io/reviews/myvr/django-celery-beat/1#-LL6bAtSAkmqRTES_Adx:-LL6bqUZ7Bhxru0sdwVI:b-8opwyg) ([raw file](https://github.com/myvr/django-celery-beat/blob/d7e39d59af718fa3df94412dd295c4ce632231ae/django_celery_beat/utils.py#L34)):*
<details><summary><i>Previously, jkasky (Jesse Kasky) wrote…</i></summary><blockquote>

`and timezone.is_aware(value):`

Just a safeguard, `timezone.localtime` calls `value.astimezone` which will fail if you pass an unaware timezone because it can't convert an unaware value to another timezone.
</blockquote></details>

Good point, Done


<!-- Sent from Reviewable.io -->

2018-08-29 21:47 UTC, jkasky approved these changes
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/myvr/django-celery-beat/1)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2018-08-29 21:47 UTC, jkasky approved these changes
> *[Reviewable](https://reviewable.io/reviews/myvr/django-celery-beat/1)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2018-08-29 22:49 UTC, jkasky approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/myvr/django-celery-beat/1#-:-LL6sAkkDK9qCc3QCKT9:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2018-08-29 22:50 UTC, merged